name: C Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build with Make
        run: make
      - name: Run executable
        run: ./main
